apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-ds
  labels:
    app: my-app
spec: 
  template:
    metadata:
      name: my-app
      labels: 
        app: yogi-app
    spec:
      containers:
        - name: nginx-container
          image: nginx 
          ports:
            - name: nginx
              protocol: TCP
              containerPort: 2049
  replicas: 2
  selector: 
    matchLabels:
      app: yogi-app
    