apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels: 
    app: yogi-app
  namespace: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx 
      ports:
        - name: nginx
          protocol: TCP
          containerPort: 123
          