apiVersion: v1
kind: Pod
metadata:
  name: joker-app
  labels:
    app: yogi-app
spec:
  containers:
    - name: http-container
      image: httpd
      ports:
        - name: http
          protocol: TCP
          containerPort: 80
      env:
      - name: "MYSQL_ROOT_PASSWORD"
        valueFrom:
          secretKeyRef:
            name: my-s
            key: DB_PASS
      - name: "MYSQL_USER"
        valueFrom:
          configMapKeyRef:
            name: my-var
            key: USER