apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-ss
  labels:
    app: yogi-app
spec: 
  template:
    metadata:
      name: yogi-app
      labels: 
        app: yogi-app
    spec:
      containers:
        - name: nginx-container
          image: nginx 
          ports:
            - name: nginx
              protocol: TCP
              containerPort: 2049
          env:
            name: "MYSQL_ROOT_PASSWORD"
            values: 
  replicas: 2
  selector: 
    matchLabels:
      app: yogi-app
    