apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mobile-app
  labels:
    app: mobile-app
spec:
  template:
    metadata:
      name: mobile-app
      labels:
        app: mobile-app
    spec:
      containers:
        - name: mobile-app
          image: yogi2112/kube-proj:mobile
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      app: mobile-app
  strategy:
    type: RollingUpdate